Document: nb
Title: Debian nb Manual
Author: <insert document author here>
Abstract: This manual describes what nb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/nb/nb.sgml.gz

Format: postscript
Files: /usr/share/doc/nb/nb.ps.gz

Format: text
Files: /usr/share/doc/nb/nb.text.gz

Format: HTML
Index: /usr/share/doc/nb/html/index.html
Files: /usr/share/doc/nb/html/*.html
